[workspace]

members = [
    "week-1/example",
    "week-1/hashmap-count",
    "week-1/hashmap-language",
    "week-1/vector-fruit-salad",
    "week-1/vecdeque-fruit-salad",
    "week-1/linked-list-fruit-salad",
]

resolver = "2"